### ISSUE TITLE
Sketch too big

### ISSUE THREAD

**Issue by dakoller** [marcuscbehrens/loralife#2]
Hi Marcus,

when I compile it for a feather32u4 lora I get

Arduino: 1.8.1 (Mac OS X), Board: "Adafruit Feather 32u4"

Der Sketch verwendet 33248 Bytes (115%) des Programmspeicherplatzes. Das Maximum sind 28672 Bytes.

Globale Variablen verwenden 1182 Bytes des dynamischen Speichers.
Der Sketch ist zu groß; unter http://www.arduino.cc/en/Guide/Troubleshooting#size finden sich Hinweise, um die Größe zu verringern.
Fehler beim Kompilieren für das Board Adafruit Feather 32u4.

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

--> how did you get it smaller or even put on the device?

Kind regards,

Daniel

**Comment by marcuscbehrens** [comment]
i need to check what i did different. might be a different ide version. i
will check.

Daniel Koller <notifications@github.com> schrieb am So. 13. Aug. 2017 um
22:24:

**Comment by marcuscbehrens** [comment]
daniel was able to resolve it somehow ...
